### ISSUE TITLE
Cannot deprecate module in private registry - "'url' must be a string"

### ISSUE THREAD

**Issue by gotofritz** [npm/npm-registry-client#120]
When I run this

    npm deprecate x "x is gone bad" --registry=https://example.com/npm/

I get that

    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "x" "x is gone bad" "--registry=https://example.com/npm/"
    npm ERR! node v4.1.0
    npm ERR! npm  v2.14.3

    npm ERR! Parameter 'url' must be a string, not undefined
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /pth/x/npm-debug.log

This is true also if I do `--registry https://example.com/npm/` (space instead of equal) or leave out the --registry parameter altogether (it's in my .npmrc).

I have been able to publish and update the module to that registry without any problems; only `deprecate` seems not to work.

**Comment by gotofritz** [comment]
Using OS X. Here's the npm-debug.log

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'deprecate',
    1 verbose cli   'x',
    1 verbose cli   'x gone bad',
    1 verbose cli   '--registry=http://example.com/npm/' ]
    2 info using npm@2.14.3
    3 info using node@v4.1.0
    4 silly mapToRegistry name x
    5 silly mapToRegistry using default registry
    6 silly mapToRegistry registry http://example.com/npm/
    7 silly mapToRegistry uri http://example.com/npm/x
    8 verbose get GET as part of write; not caching result
    9 verbose request uri http://example.com/npm/x?write=true
    10 verbose request always-auth set; sending authorization
    11 info attempt registry request try #1 at 11:33:01 AM
    12 verbose request id 06b2d6060e33ed7c
    13 http request GET http://example.com/npm/x?write=true
    14 http 200 http://example.com/npm/x?write=true
    15 silly get cb [ 200,
    15 silly get   { date: 'Fri, 09 Oct 2015 09:32:56 GMT',
    15 silly get     server: 'Nexus/2.11.1-01',
    15 silly get     'x-frame-options': 'SAMEORIGIN',
    15 silly get     'x-content-type-options': 'nosniff',
    15 silly get     'accept-ranges': 'bytes',
    15 silly get     'content-type': 'application/json',
    15 silly get     'last-modified': 'Fri, 09 Oct 2015 09:32:56 GMT',
    15 silly get     'content-length': '63950',
    15 silly get     'set-cookie': [ 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 08-Oct-2015 09:32:56 GMT' ],
    15 silly get     'keep-alive': 'timeout=5, max=100',
    15 silly get     connection: 'Keep-Alive' } ]
    16 verbose get saving x to /path/.npm/xxx/content/groups/npm-default/x_3Fwrite_3Dtrue/.cache.json
    17 verbose stack TypeError: Parameter 'url' must be a string, not undefined
    17 verbose stack     at Url.parse (url.js:90:11)
    17 verbose stack     at urlParse (url.js:84:5)
    17 verbose stack     at Url.resolve (url.js:426:29)
    17 verbose stack     at Object.urlResolve [as resolve] (url.js:422:40)
    17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/deprecate.js:41:22)
    17 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
    17 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
    17 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
    18 verbose cwd /path/work/pv-frontend-build-tools/x
    19 error Darwin 14.5.0
    20 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "deprecate" "x" "x gone bad" "--registry=http://example.com/npm/"
    21 error node v4.1.0
    22 error npm  v2.14.3
    23 error Parameter 'url' must be a string, not undefined
    24 error If you need help, you may report this error at:
    24 error     <https://github.com/npm/npm/issues>
    25 verbose exit [ 1, true ]
